/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\Werkbestanden\Leverstijl\20241101_Leverstijl\exports\ThreeIslands.gltf --transform 
Files: D:\Werkbestanden\Leverstijl\20241101_Leverstijl\exports\ThreeIslands.gltf [4.54MB] > D:\Werkbestanden\Leverstijl\Leverstijl.nl Github\eiland\ThreeIslands-transformed.glb [22.07MB] (-387%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/ThreeIslands-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="ThreeIslands">
        <group name="SK_Escalator_Steps_01_Anim_Up">
          <primitive object={nodes.SK_Escalator_Rig_Base_01} />
        </group>
        <group name="SK_Escalator_Steps_01_Anim_Down">
          <primitive object={nodes.SK_Escalator_Rig_Base_01_1} />
        </group>
        <directionalLight intensity={6.265} decay={2} color="#fff8fe" rotation={[-2.742, -0.766, 1.466]} scale={2.5} target={nodes.DirectionalLight.target}>
          <primitive object={nodes.DirectionalLight.target} position={[0, 0, -1]} />
        </directionalLight>
        <directionalLight intensity={6} decay={2} rotation={[0, -Math.PI / 2, 0]} target={nodes.Light_Source.target}>
          <primitive object={nodes.Light_Source.target} position={[0, 0, -1]} />
        </directionalLight>
        <pointLight name="Point_light_(2)" intensity={80} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(1)" intensity={30} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} />
        <spotLight intensity={80} angle={Math.PI / 3} penumbra={1} decay={2} distance={9.01} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light.target}>
          <primitive object={nodes.Spot_Light.target} position={[0, 0, -1]} />
        </spotLight>
        <pointLight name="Point_light" intensity={350} decay={2} distance={18} color="#ffe8d1" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(3)" intensity={50} decay={2} distance={5} color="#ffc5b0" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(4)" intensity={50} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(5)" intensity={20} decay={2} distance={7.5} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(6)" intensity={50} decay={2} distance={7.5} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(3)2" intensity={50} decay={2} distance={5} color="#ffc5b0" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(3)3" intensity={50} decay={2} distance={5} color="#ffc5b0" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(3)4" intensity={50} decay={2} distance={5} color="#ffc5b0" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(4)2" intensity={50} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(4)3" intensity={30} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(4)4" intensity={30} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(4)5" intensity={10} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} />
        <spotLight intensity={80} angle={Math.PI / 3} penumbra={1} decay={2} distance={9.01} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light2.target}>
          <primitive object={nodes.Spot_Light2.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={80} angle={Math.PI / 3} penumbra={1} decay={2} distance={9.01} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light3.target}>
          <primitive object={nodes.Spot_Light3.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={80} angle={Math.PI / 3} penumbra={1} decay={2} distance={9.01} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light4.target}>
          <primitive object={nodes.Spot_Light4.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={80} angle={Math.PI / 3} penumbra={1} decay={2} distance={9.01} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light5.target}>
          <primitive object={nodes.Spot_Light5.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={80} angle={Math.PI / 3} penumbra={1} decay={2} distance={9.01} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light6.target}>
          <primitive object={nodes.Spot_Light6.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={80} angle={Math.PI / 3} penumbra={1} decay={2} distance={9.01} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light7.target}>
          <primitive object={nodes.Spot_Light7.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={80} angle={Math.PI / 3} penumbra={1} decay={2} distance={9.01} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light8.target}>
          <primitive object={nodes.Spot_Light8.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={80} angle={Math.PI / 3} penumbra={1} decay={2} distance={9.01} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light9.target}>
          <primitive object={nodes.Spot_Light9.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={80} angle={Math.PI / 3} penumbra={1} decay={2} distance={9.01} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light10.target}>
          <primitive object={nodes.Spot_Light10.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={80} angle={Math.PI / 3} penumbra={1} decay={2} distance={9.01} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light11.target}>
          <primitive object={nodes.Spot_Light11.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={80} angle={Math.PI / 3} penumbra={1} decay={2} distance={9.01} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light12.target}>
          <primitive object={nodes.Spot_Light12.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={80} angle={Math.PI / 3} penumbra={1} decay={2} distance={9.01} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light13.target}>
          <primitive object={nodes.Spot_Light13.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={80} angle={Math.PI / 3} penumbra={1} decay={2} distance={9.01} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light14.target}>
          <primitive object={nodes.Spot_Light14.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={80} angle={Math.PI / 3} penumbra={1} decay={2} distance={9.01} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light15.target}>
          <primitive object={nodes.Spot_Light15.target} position={[0, 0, -1]} />
        </spotLight>
        <pointLight name="Point_light_(4)6" intensity={20} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(4)8" intensity={10} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} />
        <spotLight intensity={160} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight.target}>
          <primitive object={nodes.SpotLight.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={160} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight2.target}>
          <primitive object={nodes.SpotLight2.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={160} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight3.target}>
          <primitive object={nodes.SpotLight3.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={160} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight4.target}>
          <primitive object={nodes.SpotLight4.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={160} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight5.target}>
          <primitive object={nodes.SpotLight5.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={160} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight6.target}>
          <primitive object={nodes.SpotLight6.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={160} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight7.target}>
          <primitive object={nodes.SpotLight7.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={160} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight8.target}>
          <primitive object={nodes.SpotLight8.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={160} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight9.target}>
          <primitive object={nodes.SpotLight9.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={160} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight10.target}>
          <primitive object={nodes.SpotLight10.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={160} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight11.target}>
          <primitive object={nodes.SpotLight11.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={160} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight12.target}>
          <primitive object={nodes.SpotLight12.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={160} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight13.target}>
          <primitive object={nodes.SpotLight13.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={160} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight14.target}>
          <primitive object={nodes.SpotLight14.target} position={[0, 0, -1]} />
        </spotLight>
        <pointLight name="Point_light_(1)3" intensity={30} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} />
        <spotLight intensity={160} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight15.target}>
          <primitive object={nodes.SpotLight15.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={160} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight16.target}>
          <primitive object={nodes.SpotLight16.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.873} penumbra={1} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight17.target}>
          <primitive object={nodes.SpotLight17.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.873} penumbra={1} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight18.target}>
          <primitive object={nodes.SpotLight18.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.873} penumbra={1} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight19.target}>
          <primitive object={nodes.SpotLight19.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.873} penumbra={1} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight20.target}>
          <primitive object={nodes.SpotLight20.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.873} penumbra={1} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight21.target}>
          <primitive object={nodes.SpotLight21.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.873} penumbra={1} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight22.target}>
          <primitive object={nodes.SpotLight22.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.873} penumbra={1} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight23.target}>
          <primitive object={nodes.SpotLight23.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight24.target}>
          <primitive object={nodes.SpotLight24.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight25.target}>
          <primitive object={nodes.SpotLight25.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight26.target}>
          <primitive object={nodes.SpotLight26.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight27.target}>
          <primitive object={nodes.SpotLight27.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight28.target}>
          <primitive object={nodes.SpotLight28.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight29.target}>
          <primitive object={nodes.SpotLight29.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight30.target}>
          <primitive object={nodes.SpotLight30.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight31.target}>
          <primitive object={nodes.SpotLight31.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight32.target}>
          <primitive object={nodes.SpotLight32.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight33.target}>
          <primitive object={nodes.SpotLight33.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight34.target}>
          <primitive object={nodes.SpotLight34.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.873} penumbra={1} decay={2} distance={20} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight35.target}>
          <primitive object={nodes.SpotLight35.target} position={[0, 0, -1]} />
        </spotLight>
        <pointLight name="Point_light2" intensity={500} decay={2} distance={18} color="#ffe8d1" rotation={[0, -Math.PI / 2, 0]} />
        <spotLight intensity={50} angle={0.873} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight36.target}>
          <primitive object={nodes.SpotLight36.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.873} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight37.target}>
          <primitive object={nodes.SpotLight37.target} position={[0, 0, -1]} />
        </spotLight>
        <pointLight name="PointLight" intensity={10} decay={2} distance={5} color="#00d4ff" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight2" intensity={5} decay={2} distance={3.5} color="#ff0015" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight3" intensity={20} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight4" intensity={20} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} />
        <spotLight intensity={100} angle={0.96} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight38.target}>
          <primitive object={nodes.SpotLight38.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={100} angle={0.96} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight39.target}>
          <primitive object={nodes.SpotLight39.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={100} angle={0.96} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight40.target}>
          <primitive object={nodes.SpotLight40.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={100} angle={0.96} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight41.target}>
          <primitive object={nodes.SpotLight41.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={100} angle={0.96} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight42.target}>
          <primitive object={nodes.SpotLight42.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={100} angle={0.96} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight43.target}>
          <primitive object={nodes.SpotLight43.target} position={[0, 0, -1]} />
        </spotLight>
        <pointLight name="Point_light_(4)7" intensity={20} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(4)9" intensity={20} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(4)10" intensity={20} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(4)11" intensity={20} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(6)2" intensity={50} decay={2} distance={7.5} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(5)2" intensity={20} decay={2} distance={7.5} rotation={[0, -Math.PI / 2, 0]} />
        <spotLight intensity={160} angle={0.873} penumbra={1} decay={2} distance={20} color="#ffd6d6" rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight44.target}>
          <primitive object={nodes.SpotLight44.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={160} angle={0.873} penumbra={1} decay={2} distance={20} color="#ffd6d6" rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight45.target}>
          <primitive object={nodes.SpotLight45.target} position={[0, 0, -1]} />
        </spotLight>
        <pointLight name="PointLight5" intensity={10} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight6" intensity={10} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight7" intensity={10} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight8" intensity={10} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight9" intensity={8} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight10" intensity={8} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight11" intensity={30} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight12" intensity={10} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} />
        <spotLight intensity={30} angle={0.96} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight46.target}>
          <primitive object={nodes.SpotLight46.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.96} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight47.target}>
          <primitive object={nodes.SpotLight47.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.96} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight48.target}>
          <primitive object={nodes.SpotLight48.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.96} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight49.target}>
          <primitive object={nodes.SpotLight49.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.96} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.SpotLight50.target}>
          <primitive object={nodes.SpotLight50.target} position={[0, 0, -1]} />
        </spotLight>
        <pointLight name="PointLight13" intensity={10} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight14" intensity={10} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight15" intensity={5} decay={2} distance={6} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight16" intensity={2} decay={2} distance={5} color="#ffb300" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight17" intensity={2} decay={2} distance={5} color="#ffb300" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight18" intensity={2} decay={2} distance={5} color="#ffb300" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight19" intensity={2} decay={2} distance={5} color="#ffb300" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight20" intensity={10} decay={2} distance={5} color="#ffb300" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight21" intensity={10} decay={2} distance={5} color="#fffcd7" rotation={[0, -Math.PI / 2, 0]} />
        <spotLight intensity={10} angle={0.611} penumbra={1} decay={2} distance={4} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light16.target}>
          <primitive object={nodes.Spot_Light16.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={10} angle={0.611} penumbra={1} decay={2} distance={4} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light17.target}>
          <primitive object={nodes.Spot_Light17.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={10} angle={0.611} penumbra={1} decay={2} distance={4} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light18.target}>
          <primitive object={nodes.Spot_Light18.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={20} angle={0.873} penumbra={1} decay={2} distance={4} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light19.target}>
          <primitive object={nodes.Spot_Light19.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={20} angle={0.873} penumbra={1} decay={2} distance={4} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light20.target}>
          <primitive object={nodes.Spot_Light20.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={20} angle={0.873} penumbra={1} decay={2} distance={4} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light21.target}>
          <primitive object={nodes.Spot_Light21.target} position={[0, 0, -1]} />
        </spotLight>
        <pointLight name="PointLight22" intensity={10} decay={2} distance={5} color="#fffcd7" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight23" intensity={10} decay={2} distance={5} color="#fffcd7" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight24" intensity={10} decay={2} distance={5} color="#fffcd7" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight25" intensity={10} decay={2} distance={5} color="#fffcd7" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight26" intensity={10} decay={2} distance={5} color="#fffcd7" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight27" intensity={10} decay={2} distance={5} color="#fffcd7" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight28" intensity={10} decay={2} distance={5} color="#fffcd7" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight29" intensity={10} decay={2} distance={5} color="#fffcd7" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight30" intensity={2} decay={2} distance={5} color="#ffb300" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight31" intensity={2} decay={2} distance={5} color="#ffb300" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight32" intensity={2} decay={2} distance={5} color="#ffb300" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight33" intensity={2} decay={2} distance={5} color="#ffb300" rotation={[0, -Math.PI / 2, 0]} />
        <spotLight intensity={30} angle={0.611} penumbra={1} decay={2} distance={4} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light22.target}>
          <primitive object={nodes.Spot_Light22.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.611} penumbra={1} decay={2} distance={4} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light23.target}>
          <primitive object={nodes.Spot_Light23.target} position={[0, 0, -1]} />
        </spotLight>
        <pointLight name="PointLight34" intensity={5} decay={2} distance={5} color="#ff00be" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight35" intensity={10} decay={2} distance={5} color="#ff00be" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight36" intensity={2} decay={2} distance={5} color="#ff00be" rotation={[0, -Math.PI / 2, 0]} />
        <spotLight intensity={50} angle={Math.PI / 3} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light24.target}>
          <primitive object={nodes.Spot_Light24.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={20} angle={0.611} penumbra={1} decay={2} distance={4} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light25.target}>
          <primitive object={nodes.Spot_Light25.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={20} angle={0.611} penumbra={1} decay={2} distance={4} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light26.target}>
          <primitive object={nodes.Spot_Light26.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={20} angle={0.611} penumbra={1} decay={2} distance={5} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light27.target}>
          <primitive object={nodes.Spot_Light27.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={20} angle={0.611} penumbra={1} decay={2} distance={5} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light28.target}>
          <primitive object={nodes.Spot_Light28.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={20} angle={0.873} penumbra={1} decay={2} distance={5} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light29.target}>
          <primitive object={nodes.Spot_Light29.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={20} angle={0.873} penumbra={1} decay={2} distance={5} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light30.target}>
          <primitive object={nodes.Spot_Light30.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.611} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light31.target}>
          <primitive object={nodes.Spot_Light31.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.611} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light32.target}>
          <primitive object={nodes.Spot_Light32.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.611} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light33.target}>
          <primitive object={nodes.Spot_Light33.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.873} penumbra={1} decay={2} distance={8} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light34.target}>
          <primitive object={nodes.Spot_Light34.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.873} penumbra={1} decay={2} distance={8} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light35.target}>
          <primitive object={nodes.Spot_Light35.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={50} angle={0.873} penumbra={1} decay={2} distance={8} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light36.target}>
          <primitive object={nodes.Spot_Light36.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.611} penumbra={1} decay={2} distance={6} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light37.target}>
          <primitive object={nodes.Spot_Light37.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.611} penumbra={1} decay={2} distance={6} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light38.target}>
          <primitive object={nodes.Spot_Light38.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.611} penumbra={1} decay={2} distance={6} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light39.target}>
          <primitive object={nodes.Spot_Light39.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.611} penumbra={1} decay={2} distance={6} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light40.target}>
          <primitive object={nodes.Spot_Light40.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.611} penumbra={1} decay={2} distance={6} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light41.target}>
          <primitive object={nodes.Spot_Light41.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.611} penumbra={1} decay={2} distance={6} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light42.target}>
          <primitive object={nodes.Spot_Light42.target} position={[0, 0, -1]} />
        </spotLight>
        <pointLight name="PointLight37" intensity={2} decay={2} distance={5} color="#ffb300" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight38" intensity={2} decay={2} distance={5} color="#ffb300" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight39" intensity={2} decay={2} distance={5} color="#ffb300" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight40" intensity={2} decay={2} distance={5} color="#ffb300" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight41" intensity={2} decay={2} distance={5} color="#ffb300" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight42" intensity={2} decay={2} distance={5} color="#ffb300" rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight43" intensity={10} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight44" intensity={10} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight45" intensity={10} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="PointLight46" intensity={10} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} />
        <spotLight intensity={30} angle={0.611} penumbra={1} decay={2} distance={6} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light43.target}>
          <primitive object={nodes.Spot_Light43.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.611} penumbra={1} decay={2} distance={6} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light44.target}>
          <primitive object={nodes.Spot_Light44.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.611} penumbra={1} decay={2} distance={6} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light45.target}>
          <primitive object={nodes.Spot_Light45.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.611} penumbra={1} decay={2} distance={6} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light46.target}>
          <primitive object={nodes.Spot_Light46.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.611} penumbra={1} decay={2} distance={6} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light47.target}>
          <primitive object={nodes.Spot_Light47.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.611} penumbra={1} decay={2} distance={6} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light48.target}>
          <primitive object={nodes.Spot_Light48.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.611} penumbra={1} decay={2} distance={6} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light49.target}>
          <primitive object={nodes.Spot_Light49.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.611} penumbra={1} decay={2} distance={6} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light50.target}>
          <primitive object={nodes.Spot_Light50.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={30} angle={0.611} penumbra={1} decay={2} distance={6} color="#ffe7ab" rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light51.target}>
          <primitive object={nodes.Spot_Light51.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light52.target}>
          <primitive object={nodes.Spot_Light52.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light53.target}>
          <primitive object={nodes.Spot_Light53.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light54.target}>
          <primitive object={nodes.Spot_Light54.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light55.target}>
          <primitive object={nodes.Spot_Light55.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light56.target}>
          <primitive object={nodes.Spot_Light56.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light57.target}>
          <primitive object={nodes.Spot_Light57.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light58.target}>
          <primitive object={nodes.Spot_Light58.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light59.target}>
          <primitive object={nodes.Spot_Light59.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light60.target}>
          <primitive object={nodes.Spot_Light60.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light61.target}>
          <primitive object={nodes.Spot_Light61.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light62.target}>
          <primitive object={nodes.Spot_Light62.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light63.target}>
          <primitive object={nodes.Spot_Light63.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light64.target}>
          <primitive object={nodes.Spot_Light64.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light65.target}>
          <primitive object={nodes.Spot_Light65.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light66.target}>
          <primitive object={nodes.Spot_Light66.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light67.target}>
          <primitive object={nodes.Spot_Light67.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light68.target}>
          <primitive object={nodes.Spot_Light68.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light69.target}>
          <primitive object={nodes.Spot_Light69.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light70.target}>
          <primitive object={nodes.Spot_Light70.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light71.target}>
          <primitive object={nodes.Spot_Light71.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light72.target}>
          <primitive object={nodes.Spot_Light72.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light73.target}>
          <primitive object={nodes.Spot_Light73.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light74.target}>
          <primitive object={nodes.Spot_Light74.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light75.target}>
          <primitive object={nodes.Spot_Light75.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light76.target}>
          <primitive object={nodes.Spot_Light76.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={250} angle={0.611} penumbra={1} decay={2} distance={15} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light77.target}>
          <primitive object={nodes.Spot_Light77.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={150} angle={0.611} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light78.target}>
          <primitive object={nodes.Spot_Light78.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={150} angle={0.611} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light79.target}>
          <primitive object={nodes.Spot_Light79.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={150} angle={0.611} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light80.target}>
          <primitive object={nodes.Spot_Light80.target} position={[0, 0, -1]} />
        </spotLight>
        <spotLight intensity={150} angle={0.611} penumbra={1} decay={2} distance={10} rotation={[0, -Math.PI / 2, 0]} target={nodes.Spot_Light81.target}>
          <primitive object={nodes.Spot_Light81.target} position={[0, 0, -1]} />
        </spotLight>
        <pointLight name="Point_light_(1)4" intensity={12} decay={2} distance={8} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(1)5" intensity={10} decay={2} distance={8} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(1)6" intensity={5} decay={2} distance={8} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(1)7" intensity={8} decay={2} distance={8} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(1)8" intensity={5} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light_(1)9" intensity={5} decay={2} distance={5} rotation={[0, -Math.PI / 2, 0]} />
        <pointLight name="Point_light3" intensity={100} decay={2} distance={18} color="#ffe8d1" rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Cube_127" geometry={nodes.Cube_127.geometry} material={materials.WorldGridMaterial} position={[-18.607, -0.134, -9.367]} />
        <mesh name="Liver_Island" geometry={nodes.Liver_Island.geometry} material={materials.Ground_Lp_Liver_Island} position={[-2.797, -1.1, 2.161]} scale={[1, 1.5, 1]} />
        <mesh name="Road1" geometry={nodes.Road1.geometry} material={materials.Road_Road1} />
        <mesh name="Cylinder_012" geometry={nodes.Cylinder_012.geometry} material={materials.Gas_station_service_Cylinder_012} position={[-7.596, -0.128, -8.107]} />
        <mesh name="Cube_055" geometry={nodes.Cube_055.geometry} material={materials.Factory_Cube_055} position={[0, 0.008, 0]} />
        <mesh name="Cube_062" geometry={nodes.Cube_062.geometry} material={materials.Harbour_2_Cube_062} position={[-15.215, -0.842, 22.751]} />
        <mesh name="rock_8" geometry={nodes.rock_8.geometry} material={materials.Lighthouse_rock_8} position={[-49.393, -2.779, 28.314]} />
        <mesh name="Cube_091" geometry={nodes.Cube_091.geometry} material={materials.Harbour_Cube_091} position={[-15.215, -0.842, 22.751]} />
        <mesh name="Cube_176" geometry={nodes.Cube_176.geometry} material={materials.Object_Cube_176} position={[-15.215, -0.842, 22.751]} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials.Noria_Cylinder} position={[-25.62, -1.289, 23.106]} rotation={[0, Math.PI / 6, 0]} scale={1.5} />
        <mesh name="Cube_166" geometry={nodes.Cube_166.geometry} material={materials.Object_Cube_166} position={[-25.62, -1.289, 23.106]} rotation={[0, Math.PI / 6, 0]} scale={1.5} />
        <mesh name="Ground_Hospital" geometry={nodes.Ground_Hospital.geometry} material={materials.Grounds_Ground_Hospital} position={[11.316, -0.04, 6.511]} />
        <mesh name="Isla_006" geometry={nodes.Isla_006.geometry} material={materials.Market_Isla_006} position={[-18.607, -0.134, -9.367]} />
        <mesh name="Ground_square" geometry={nodes.Ground_square.geometry} material={materials.Grounds_Ground_square} position={[-13.388, -0.078, -3.365]} />
        <mesh name="Car_2_002" geometry={nodes.Car_2_002.geometry} material={materials.Cars_Car_2_002} position={[-5.219, 0.011, -8.865]} />
        <mesh name="House_017" geometry={nodes.House_017.geometry} material={materials.MI_M_House_017_Vistor_houses_4C40EE6046AC9F9F87208ABA6167808C} position={[0, 0.038, 0]} />
        <group name="Hoarding_001" position={[-13.201, 0.068, -18.396]}>
          <mesh name="Hoarding_001_1" geometry={nodes.Hoarding_001_1.geometry} material={materials.Hoarding_Hoarding_001} />
          <mesh name="Hoarding_001_2" geometry={nodes.Hoarding_001_2.geometry} material={materials.PaletteMaterial001} />
        </group>
        <mesh name="Cinema_005" geometry={nodes.Cinema_005.geometry} material={materials.Cinema_Cinema_005} position={[-26.126, 0.052, -7.385]} rotation={[0, -0.825, 0]} />
        <mesh name="Text_002" geometry={nodes.Text_002.geometry} material={materials.Text_and_gym_park_Text_002} position={[-7.596, -0.128, -8.107]} />
        <mesh name="Cube_058" geometry={nodes.Cube_058.geometry} material={materials.MI_M_Cube_058_Object_D3A5793441F8A441BBC123BBE0AA4166} position={[0, 0.038, 0]} />
        <mesh name="House_018" geometry={nodes.House_018.geometry} material={materials.Vistor_houses_House_018} position={[0, 0.038, 0]} />
        <mesh name="Taxi_002" geometry={nodes.Taxi_002.geometry} material={materials.Cars_Car_2_002} position={[-20, 0.106, 10.511]} rotation={[0, 0.098, 0]} />
        <mesh name="Cube_174" geometry={nodes.Cube_174.geometry} material={materials.Park_Cube_174} position={[-21.059, 0.058, 9.308]} rotation={[-Math.PI, 1.215, -Math.PI]} />
        <mesh name="House_016" geometry={nodes.House_016.geometry} material={materials.MI_M_House_016_MI_M_House_016_Vistor_houses_B82CAA6241DA4A41A3D56E8385808B7C_9AF0CA334ED678A17A57B68128F02DF5} position={[0, 0.038, 0]} />
        <mesh name="Cube_041" geometry={nodes.Cube_041.geometry} material={materials.MI_M_Cube_041_Object_A022A0B445720BAC046B97ABA2EAADFE} position={[-11.236, 0.046, 8.621]} />
        <mesh name="Poste_007" geometry={nodes.Poste_007.geometry} material={materials.Market_Poste_007} position={[11.316, -0.04, 6.511]} />
        <mesh name="Isla_002" geometry={nodes.Isla_002.geometry} material={materials.Factory_Isla_002} position={[11.316, -0.04, 6.511]} />
        <mesh name="Cube_051" geometry={nodes.Cube_051.geometry} material={materials.Hospital_Cube_051} position={[11.316, -0.04, 6.511]} />
        <mesh name="Cylinder_006" geometry={nodes.Cylinder_006.geometry} material={materials.Tree_and_pot_Cylinder_006} position={[11.316, -0.04, 6.511]} />
        <mesh name="SM_Generic_Tree_04" geometry={nodes.SM_Generic_Tree_04.geometry} material={materials.Mat_PolygonPrototype_Bright} position={[-2.598, 0.748, 11.401]} />
        <mesh name="SM_Generic_TreeStump_01" geometry={nodes.SM_Generic_TreeStump_01.geometry} material={materials.Mat_PolygonPrototype_01} position={[-6.991, 0.05, 14.006]} />
        <mesh name="SM_Generic_Water_Plane_01" geometry={nodes.SM_Generic_Water_Plane_01.geometry} material={materials.PaletteMaterial002} position={[16.554, 0.76, 37.028]} />
        <mesh name="File_Fbx_basketball_stadium__003" geometry={nodes.File_Fbx_basketball_stadium__003.geometry} material={materials.Pack_City} position={[-16.478, 0, 4.897]} rotation={[Math.PI, -1.56, Math.PI]} scale={0.901} />
        <mesh name="Plane2" geometry={nodes.Plane2.geometry} material={materials.logo_paars_metslogan_Mat} position={[-28.495, 1.8, -0.955]} rotation={[Math.PI / 2, 0, 0.932]} scale={[2.737, 1, 1.43]} />
        <mesh name="video_screen_Island" geometry={nodes.video_screen_Island.geometry} material={materials.PaletteMaterial003} position={[-13.215, 3.806, -18.1]} rotation={[Math.PI / 2, 0, 0.053]} scale={[4.033, 1, 2.162]} />
        <mesh name="SM_Sign_Flag_03_Pivot_3" geometry={nodes.SM_Sign_Flag_03_Pivot_3.geometry} material={materials.M_PolygonShops_Signs_01} position={[-29.043, 0.108, 2.588]} rotation={[Math.PI, -0.964, Math.PI]} scale={0.696} />
        <group name="SM_Prop_Planter_Box_01_(7)2" position={[-23.186, 0.185, -0.471]} rotation={[0, 0.348, 0]} scale={0.403}>
          <mesh name="SM_Prop_Planter_Box_01" geometry={nodes.SM_Prop_Planter_Box_01.geometry} material={materials.MI_PolygonShops_Base_Brick_Red_01} />
          <mesh name="SM_Prop_Planter_Box_01_1" geometry={nodes.SM_Prop_Planter_Box_01_1.geometry} material={materials.MI_PolygonShops_01_A} />
        </group>
        <mesh name="SM_Prop_Cafe_Shaker_Pepper_01_(2)2" geometry={nodes['SM_Prop_Cafe_Shaker_Pepper_01_(2)2'].geometry} material={materials.PaletteMaterial004} position={[-25.93, 0.552, -2.332]} scale={0.696} />
        <mesh name="SM_Veh_Food_Trailer_01_Preset6" geometry={nodes.SM_Veh_Food_Trailer_01_Preset6.geometry} material={materials.MI_PolygonShops_Base_Wood_02} position={[-20.241, 0.044, -1.6]} rotation={[0, 0.223, 0]} scale={0.435} />
        <mesh name="SM_Generic_CloudRing_01" geometry={nodes.SM_Generic_CloudRing_01.geometry} material={materials.PaletteMaterial005} />
        <mesh name="SM_Prop_Cafe_Sauce_Box_02" geometry={nodes.SM_Prop_Cafe_Sauce_Box_02.geometry} material={materials.MI_PolygonShops_02_A} />
        <mesh name="SM_Prop_Barber_Clippers_01_(7)" geometry={nodes['SM_Prop_Barber_Clippers_01_(7)'].geometry} material={materials.MI_PolygonShops_04_C} />
        <mesh name="SM_Prop_Barber_Spray_Bottle_01_(7)" geometry={nodes['SM_Prop_Barber_Spray_Bottle_01_(7)'].geometry} material={materials.MI_PolygonShops_03_A} />
        <mesh name="SM_Prop_Arcade_Machine_Basic_01_(2)" geometry={nodes['SM_Prop_Arcade_Machine_Basic_01_(2)'].geometry} material={materials.MI_PolygonShops_04_A} />
        <mesh name="SM_Prop_Hunting_Fishing_Lure_01_(6)" geometry={nodes['SM_Prop_Hunting_Fishing_Lure_01_(6)'].geometry} material={materials.MI_PolygonShops_01_B} />
        <mesh name="SM_Prop_Hunting_Fishing_Lure_01_(5)" geometry={nodes['SM_Prop_Hunting_Fishing_Lure_01_(5)'].geometry} material={materials.MI_PolygonShops_02_B} />
        <mesh name="SM_Prop_Hunting_Fishing_Lure_01_(2)" geometry={nodes['SM_Prop_Hunting_Fishing_Lure_01_(2)'].geometry} material={materials.MI_PolygonShops_03_B} />
        <mesh name="SM_Env_Ground_ParkingLines_01_(17)" geometry={nodes['SM_Env_Ground_ParkingLines_01_(17)'].geometry} material={materials.MI_PolygonShops_Road_Dirt_02} />
        <mesh name="SM_Env_Sidewalk_02_(138)" geometry={nodes['SM_Env_Sidewalk_02_(138)'].geometry} material={materials.MI_PolygonShops_Road_01} />
        <mesh name="SM_Bld_Base_Wall_01_(303)" geometry={nodes['SM_Bld_Base_Wall_01_(303)'].geometry} material={materials.MI_PolygonShops_Toilet_01} />
        <mesh name="SM_Prop_Kitchen_Deep_Fryer_Net_01" geometry={nodes.SM_Prop_Kitchen_Deep_Fryer_Net_01.geometry} material={materials.M_PolygonShops_Wire_01} />
        <mesh name="SM_Prop_Ad_Screen_01_(2)" geometry={nodes['SM_Prop_Ad_Screen_01_(2)'].geometry} material={materials['M_ScrollingBoard_SM_Prop_Ad_Screen_01 (2)']} />
        <mesh name="SM_Prop_Cafe_Napkin_Dispenser_01" geometry={nodes.SM_Prop_Cafe_Napkin_Dispenser_01.geometry} material={materials.MI_PolygonShops_03_C} />
        <mesh name="SM_Prop_Shop_Shelf_02_(7)" geometry={nodes['SM_Prop_Shop_Shelf_02_(7)'].geometry} material={materials.MI_PolygonShops_02_C} />
        <mesh name="SM_Prop_Computer_Camera_Small_03_(2)" geometry={nodes['SM_Prop_Computer_Camera_Small_03_(2)'].geometry} material={materials.MI_PolygonShops_01_C} />
        <mesh name="SM_Prop_Sport_Basketball_02" geometry={nodes.SM_Prop_Sport_Basketball_02.geometry} material={materials.MI_PolygonShops_04_B} />
        <mesh name="SM_Prop_Sport_Snowboard_01" geometry={nodes.SM_Prop_Sport_Snowboard_01.geometry} material={materials.MI_PolygonShops_Base_Concrete_Blocks_01} />
        <mesh name="SM_Prop_Mall_Map_01_(5)" geometry={nodes['SM_Prop_Mall_Map_01_(5)'].geometry} material={materials.M_PolygonShops_Mall_Map_01} />
        <mesh name="SM_Sign_Board_21_(10)" geometry={nodes['SM_Sign_Board_21_(10)'].geometry} material={materials.MI_PolygonShops_Tile_02} />
        <mesh name="SM_Prop_Diorama_01" geometry={nodes.SM_Prop_Diorama_01.geometry} material={materials.MI_PolygonShops_Cobbletone_01} />
        <mesh name="SM_Env_Ground_ParkingLines_01_(14)" geometry={nodes['SM_Env_Ground_ParkingLines_01_(14)'].geometry} material={materials.MI_PolygonShops_Road_WhiteLines_01} />
        <mesh name="SM_Bld_Base_Floor_Combined_01_(93)" geometry={nodes['SM_Bld_Base_Floor_Combined_01_(93)'].geometry} material={materials.MI_PolygonShops_Base_Carpet_01} />
        <mesh name="SM_Env_Ground_ParkingLines_01_(18)" geometry={nodes['SM_Env_Ground_ParkingLines_01_(18)'].geometry} material={materials.MI_PolygonShops_Road_Disabled_01} />
        <mesh name="SM_Env_Ground_LoadingZone_01_(6)" geometry={nodes['SM_Env_Ground_LoadingZone_01_(6)'].geometry} material={materials.MI_PolygonShops_Road_YellowDiagonal_01} />
        <mesh name="SM_Env_Ground_ParkingLines_01_(23)" geometry={nodes['SM_Env_Ground_ParkingLines_01_(23)'].geometry} material={materials.MI_PolygonShops_Road_Dirt_01} />
        <group name="SM_Bld_Wall_Window_Grid_01_(2)">
          <mesh name="SM_Bld_Wall_Window_Grid_01" geometry={nodes.SM_Bld_Wall_Window_Grid_01.geometry} material={materials.MI_PolygonShops_Base_Wood_01} />
          <mesh name="SM_Bld_Wall_Window_Grid_01_1" geometry={nodes.SM_Bld_Wall_Window_Grid_01_1.geometry} material={materials.MI_PolygonShops_Brick_Coloured_01} />
        </group>
        <mesh name="SM_Bld_Base_Wall_Half_01_(10)" geometry={nodes['SM_Bld_Base_Wall_Half_01_(10)'].geometry} material={materials.MI_PolygonShops_Base_Brick_White_01} />
        <mesh name="SM_Bld_Base_Pillar_02_(13)" geometry={nodes['SM_Bld_Base_Pillar_02_(13)'].geometry} material={materials.MI_PolygonShops_Concrete_Blocks_02} />
        <mesh name="SM_Bld_Base_Wall_Half_01_(36)" geometry={nodes['SM_Bld_Base_Wall_Half_01_(36)'].geometry} material={materials.MI_PolygonShops_Concrete_01} />
        <mesh name="SM_Bld_Base_Floor_01_(124)" geometry={nodes['SM_Bld_Base_Floor_01_(124)'].geometry} material={materials.MI_PolygonShops_Base_Tile_01} />
        <mesh name="SM_Bld_Base_Floor_01_(281)" geometry={nodes['SM_Bld_Base_Floor_01_(281)'].geometry} material={materials.MI_PolygonShops_Base_Blank_01} />
        <mesh name="SM_Bld_Base_Floor_01_(251)" geometry={nodes['SM_Bld_Base_Floor_01_(251)'].geometry} material={materials.MI_PolygonShops_Tile_04} />
        <mesh name="SM_Bld_Base_Floor_Combined_01_(543)" geometry={nodes['SM_Bld_Base_Floor_Combined_01_(543)'].geometry} material={materials.MI_PolygonShops_Carpet_02} />
        <mesh name="SM_Bld_Trim_Ceiling_01_(22)" geometry={nodes['SM_Bld_Trim_Ceiling_01_(22)'].geometry} material={materials.MI_PolygonShops_Coloured_01} />
        <mesh name="SM_Bld_Base_Floor_Combined_01_(525)" geometry={nodes['SM_Bld_Base_Floor_Combined_01_(525)'].geometry} material={materials.MI_PolygonShops_Carpet_03} />
        <mesh name="SM_Bld_Wall_Shutter_03_Bars" geometry={nodes.SM_Bld_Wall_Shutter_03_Bars.geometry} material={materials.M_PolygonShops_Shutter_01} />
        <mesh name="SM_Bld_Base_Floor_01_(289)" geometry={nodes['SM_Bld_Base_Floor_01_(289)'].geometry} material={materials.MI_PolygonShops_Tile_03} />
        <mesh name="SM_Bld_Base_Floor_01_(337)" geometry={nodes['SM_Bld_Base_Floor_01_(337)'].geometry} material={materials.MI_PolygonShops_Carpet_01} />
        <mesh name="SM_Bld_Base_Floor_01_(319)" geometry={nodes['SM_Bld_Base_Floor_01_(319)'].geometry} material={materials.MI_PolygonShops_Tile_01} />
        <mesh name="SM_Bld_ShopFront_02" geometry={nodes.SM_Bld_ShopFront_02.geometry} material={materials.MI_PolygonShops_Stone_01} />
        <mesh name="SM_Bld_Base_Wall_Half_01_(69)" geometry={nodes['SM_Bld_Base_Wall_Half_01_(69)'].geometry} material={materials.MI_PolygonShops_Arcade_01} />
        <mesh name="SM_Bld_Base_Wall_Half_01_(5)" geometry={nodes['SM_Bld_Base_Wall_Half_01_(5)'].geometry} material={materials.MI_PolygonShops_Mat_01} />
        <mesh name="SM_Bld_Base_Floor_Combined_01_(468)" geometry={nodes['SM_Bld_Base_Floor_Combined_01_(468)'].geometry} material={materials.MI_PolygonShops_Carpet_02_Alt_02} />
        <mesh name="SM_Bld_Base_Wall_01_(332)" geometry={nodes['SM_Bld_Base_Wall_01_(332)'].geometry} material={materials.MI_PolygonShops_Cladding_01} />
        <mesh name="SM_Bld_Base_Wall_01_(91)" geometry={nodes['SM_Bld_Base_Wall_01_(91)'].geometry} material={materials.MI_PolygonShops_Concrete_Stripe_01} />
        <mesh name="SM_Bld_Base_Floor_01_(321)" geometry={nodes['SM_Bld_Base_Floor_01_(321)'].geometry} material={materials.MI_PolygonShops_Arcade_02} />
        <mesh name="SM_Prop_Gym_Tredmill_01_Belt_01" geometry={nodes.SM_Prop_Gym_Tredmill_01_Belt_01.geometry} material={materials.M_PolygonShops_Treadmill_Mat_01} />
        <mesh name="SkySphereMesh" geometry={nodes.SkySphereMesh.geometry} material={materials.MID_M_Sky_Panning_Clouds2_0_SkySphereMesh} />
        <skinnedMesh name="SK_Escalator_Steps_01_instance_0" geometry={nodes.SK_Escalator_Steps_01_instance_0.geometry} material={materials.MI_PolygonShops_01_A} skeleton={nodes.SK_Escalator_Steps_01_instance_0.skeleton} />
        <skinnedMesh name="SK_Escalator_Steps_01_instance_1" geometry={nodes.SK_Escalator_Steps_01_instance_1.geometry} material={materials.MI_PolygonShops_01_A} skeleton={nodes.SK_Escalator_Steps_01_instance_1.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/ThreeIslands-transformed.glb')
